defaults:
  - _self_
  #- data: poas.yaml
  #- data: her2.yaml
  - data: cov.yaml
  - model: denoise.yaml
  - callbacks: default.yaml
  - logger: wandb.yaml
  - trainer: default.yaml
  - setup: default.yaml

dryrun: false
